# Generated by Django 3.2.6 on 2021-09-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_id_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_empleado',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
