# Generated by Django 3.2.6 on 2021-10-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employee_lastname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Empleado/a', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_empleado',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Cedula de ciudadanía'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lastname',
            field=models.CharField(max_length=50, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre(s)'),
        ),
    ]
