# Generated by Django 3.2.6 on 2021-10-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='n_room',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Número de sala'),
        ),
    ]
