# Generated by Django 3.2.6 on 2021-10-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_rooms_n_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='funtion',
            field=models.CharField(choices=[('Sala de espera', 'Sala de espera'), ('Quirófano', 'Quirófano'), ('Quirófano Hibrido', 'Quirófano Hibrido'), ('Sala de preparación', 'Sala de preparación'), ('Sala de espera', 'Sala de espera'), ('Laboratorio', 'Laboratorio'), ('Consultorio', 'Consultorio')], max_length=30, verbose_name='Función de la sala'),
        ),
    ]
