# Generated by Django 3.2.6 on 2021-09-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_rename_names_patients_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='rh',
            field=models.CharField(choices=[('A positivo', 'A+'), ('A negativo', 'A-'), ('O positivo', 'O+'), ('O negativo', 'O-'), ('AB positivo', 'AB+'), ('AB negativo', 'AB-'), ('B positivo', 'B+'), ('B negativo', 'B-')], default='A+', max_length=15, verbose_name='Tipo de sangre'),
        ),
    ]
